import mongoose, { Schema } from "mongoose";

// Define the Supplier schema
const supplierSchema = new Schema(
  {
    supplierId: {
      type: Schema.Types.ObjectId, // Auto-generated by MongoDB
    },
    address: {
      type: String,
      trim: true,
    },
    total_revenue: {
      type: Number,
    },
    ESGScore: {
      type: Number,
      min: 0,
      max: 100, // Assuming ESG score is between 0 and 100
    },
    panCard: {
      type: String,
      trim: true,
      unique: true, // PAN should be unique to each supplier
    },
    GSTNo: {
      type: String,
      trim: true,
      unique: true, // GST No should also be unique
    },
    data: {
      type: [Object], // Array of objects
      default: [], // Default to an empty array
    },
    esgReport: {
      type: Schema.Types.ObjectId,
      ref: "ESGReport",
    },
    suppliesTo: [
      {
        companyName: {
          type: String,
          trim: true,
        },
        companyID: {
          type: Schema.Types.ObjectId,
          ref: "Company",  
        },
        date: {
          type: Date,
        },
      },
    ],
    questions: [
      {
        question: {
          type: String,
          required: true,
        },
        answer: {
          type: String,
          required: false, // Answer can be optional if it's not yet provided
        },
        timePeriod: {
          type: String, // Could represent something like "Q1 2024", "2024-2025", etc.
          required: true,
          trim: true,
        },
      },
    ],
  },
  {
    timestamps: true, // Adds createdAt and updatedAt fields automatically
  }
);

export const Supplier = mongoose.model("Supplier", supplierSchema);
